<?php

namespace LMS;
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $table = 'order';
    
	
    public function Deliveryaddress()
    {
        return $this->hasOne('LMS\Deliveryaddress','order_id','id');        
    }
	public function Billingaddress()
    {
        return $this->hasOne('LMS\Billingaddress','order_id','id');        
    }
    public function Billing()
    {
        return $this->hasOne('LMS\Billing','order_id','id');        
    }
    public function Items()
    {
        return $this->hasMany('LMS\Orderitems','order_id','id');        
    }
    /*public function Item_group()
    {   
        $itemString = '<span>';
        $items = $this->hasMany('LMS\Orderitems','order_id','id')->pluck('name');
        foreach($items as $t) {
            $itemString .= "<div>". $t."</div>"; 
        }
        $itemString .="</span>"; 
        return $itemString ? $itemString : '-';
    }*/
	public function Item_group()
    {   
        $itemString = '<span>';
        $items = $this->hasMany('LMS\Orderitems','order_id','id')->get();
        foreach($items as $t) {
            $itemString .= "<div> Name : ". $t->Name."</div>"; 
            $itemString .= "<div> Sku : ". $t->SupplierOrderlineNumber."</div>"; 
            
        }
        $itemString .="</span>"; 
        return $itemString ? $itemString : '-';
    }
    
	public function Status()
    {
        return $this->hasOne('LMS\Orderstatus','order_id','id');        
    }

    	public function complateorder()
    {
        return $this->hasMany('LMS\Orderstatus','order_id','id')->where('status','=', 'DES');;       
    }
    public function Quickbook() {
        return $this->hasOne('LMS\InvoiceQuickBook', 'order_id', 'id');
    }


    //currency
    public static function getCurrencies(){
        $currencies = array(
        array('code' =>'AFN' , 'name' => 'Afghani', 'symbol' => '؋' ),
        array('code' =>'ALL' , 'name' => 'Lek', 'symbol' => 'Lek' ),
        array('code' =>'ANG' , 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ' ),
        array('code' =>'ARS' , 'name' => 'Argentine Peso', 'symbol' => '$' ),
        array('code' =>'AUD' , 'name' => 'Australian Dollar', 'symbol' => '$' ),
        array('code' =>'AWG' , 'name' => 'Aruban Guilder', 'symbol' => 'ƒ' ),
        array('code' =>'AZN' , 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман' ),
        array('code' =>'BAM' , 'name' => 'Convertible Marks', 'symbol' => 'KM' ),
        array('code' =>'BBD' , 'name' => 'Barbados Dollar', 'symbol' => '$' ),
        array('code' =>'BGN' , 'name' => 'Bulgarian Lev', 'symbol' => 'лв' ),
        array('code' =>'BMD' , 'name' => 'Bermudian Dollar', 'symbol' => '$' ),
        array('code' =>'BND' , 'name' => 'Brunei Dollar', 'symbol' => '$' ),
        array('code' =>'BOB' , 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b' ),
        array('code' =>'BRL' , 'name' => 'Brazilian Real', 'symbol' => 'R$' ),
        array('code' =>'BSD' , 'name' => 'Bahamian Dollar', 'symbol' => '$' ),
        array('code' =>'BWP' , 'name' => 'Pula', 'symbol' => 'P' ),
        array('code' =>'BYR' , 'name' => 'Belarussian Ruble', 'symbol' => 'p.' ),
        array('code' =>'BZD' , 'name' => 'Belize Dollar', 'symbol' => 'BZ$' ),
        array('code' =>'CAD' , 'name' => 'Canadian Dollar', 'symbol' => '$' ),
        array('code' =>'CHF' , 'name' => 'Swiss Franc', 'symbol' => 'CHF' ),
        array('code' =>'CLP' , 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$' ),
        array('code' =>'CNY' , 'name' => 'Yuan Renminbi', 'symbol' => '¥' ),
        array('code' =>'COP' , 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$' ),
        array('code' =>'CRC' , 'name' => 'Costa Rican Colon', 'symbol' => '₡' ),
        array('code' =>'CUP' , 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱' ),
        array('code' =>'CZK' , 'name' => 'Czech Koruna', 'symbol' => 'Kč' ),
        array('code' =>'DKK' , 'name' => 'Danish Krone', 'symbol' => 'kr' ),
        array('code' =>'DOP' , 'name' => 'Dominican Peso', 'symbol' => 'RD$' ),
        array('code' =>'EGP' , 'name' => 'Egyptian Pound', 'symbol' => '£' ),
        array('code' =>'EUR' , 'name' => 'Euro', 'symbol' => '€' ),
        array('code' =>'FJD' , 'name' => 'Fiji Dollar', 'symbol' => '$' ),
        array('code' =>'FKP' , 'name' => 'Falkland Islands Pound', 'symbol' => '£' ),
        array('code' =>'GBP' , 'name' => 'Pound Sterling', 'symbol' => '£' ),
        array('code' =>'GIP' , 'name' => 'Gibraltar Pound', 'symbol' => '£' ),
        array('code' =>'GTQ' , 'name' => 'Quetzal', 'symbol' => 'Q' ),
        array('code' =>'GYD' , 'name' => 'Guyana Dollar', 'symbol' => '$' ),
        array('code' =>'HKD' , 'name' => 'Hong Kong Dollar', 'symbol' => '$' ),
        array('code' =>'HNL' , 'name' => 'Lempira', 'symbol' => 'L' ),
        array('code' =>'HRK' , 'name' => 'Croatian Kuna', 'symbol' => 'kn' ),
        array('code' =>'HUF' , 'name' => 'Forint', 'symbol' => 'Ft' ),
        array('code' =>'IDR' , 'name' => 'Rupiah', 'symbol' => 'Rp' ),
        array('code' =>'ILS' , 'name' => 'New Israeli Sheqel', 'symbol' => '₪' ),
        array('code' =>'INR' , 'name' => 'Indian Rupee', 'symbol' => '₹' ),
        array('code' =>'IRR' , 'name' => 'Iranian Rial', 'symbol' => '﷼' ),
        array('code' =>'ISK' , 'name' => 'Iceland Krona', 'symbol' => 'kr' ),
        array('code' =>'JMD' , 'name' => 'Jamaican Dollar', 'symbol' => 'J$' ),
        array('code' =>'JPY' , 'name' => 'Yen', 'symbol' => '¥' ),
        array('code' =>'KGS' , 'name' => 'Som', 'symbol' => 'лв' ),
        array('code' =>'KHR' , 'name' => 'Riel', 'symbol' => '៛' ),
        array('code' =>'KPW' , 'name' => 'North Korean Won', 'symbol' => '₩' ),
        array('code' =>'KRW' , 'name' => 'Won', 'symbol' => '₩' ),
        array('code' =>'KYD' , 'name' => 'Cayman Islands Dollar', 'symbol' => '$' ),
        array('code' =>'KZT' , 'name' => 'Tenge', 'symbol' => 'лв' ),
        array('code' =>'LAK' , 'name' => 'Kip', 'symbol' => '₭' ),
        array('code' =>'LBP' , 'name' => 'Lebanese Pound', 'symbol' => '£' ),
        array('code' =>'LKR' , 'name' => 'Sri Lanka Rupee', 'symbol' => '₨' ),
        array('code' =>'LRD' , 'name' => 'Liberian Dollar', 'symbol' => '$' ),
        array('code' =>'LTL' , 'name' => 'Lithuanian Litas', 'symbol' => 'Lt' ),
        array('code' =>'LVL' , 'name' => 'Latvian Lats', 'symbol' => 'Ls' ),
        array('code' =>'MKD' , 'name' => 'Denar', 'symbol' => 'ден' ),
        array('code' =>'MNT' , 'name' => 'Tugrik', 'symbol' => '₮' ),
        array('code' =>'MUR' , 'name' => 'Mauritius Rupee', 'symbol' => '₨' ),
        array('code' =>'MXN' , 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI)', 'symbol' => '$' ),
        array('code' =>'MYR' , 'name' => 'Malaysian Ringgit', 'symbol' => 'RM' ),
        array('code' =>'MZN' , 'name' => 'Metical', 'symbol' => 'MT' ),
        array('code' =>'NGN' , 'name' => 'Naira', 'symbol' => '₦' ),
        array('code' =>'NIO' , 'name' => 'Cordoba Oro', 'symbol' => 'C$' ),
        array('code' =>'NOK' , 'name' => 'Norwegian Krone', 'symbol' => 'kr' ),
        array('code' =>'NPR' , 'name' => 'Nepalese Rupee', 'symbol' => '₨' ),
        array('code' =>'NZD' , 'name' => 'New Zealand Dollar', 'symbol' => '$' ),
        array('code' =>'OMR' , 'name' => 'Rial Omani', 'symbol' => '﷼' ),
        array('code' =>'PAB' , 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.' ),
        array('code' =>'PEN' , 'name' => 'Nuevo Sol', 'symbol' => 'S/.' ),
        array('code' =>'PHP' , 'name' => 'Philippine Peso', 'symbol' => 'Php' ),
        array('code' =>'PKR' , 'name' => 'Pakistan Rupee', 'symbol' => '₨' ),
        array('code' =>'PLN' , 'name' => 'Zloty', 'symbol' => 'zł' ),
        array('code' =>'PYG' , 'name' => 'Guarani', 'symbol' => 'Gs' ),
        array('code' =>'QAR' , 'name' => 'Qatari Rial', 'symbol' => '﷼' ),
        array('code' =>'RON' , 'name' => 'New Leu', 'symbol' => 'lei' ),
        array('code' =>'RSD' , 'name' => 'Serbian Dinar', 'symbol' => 'Дин.' ),
        array('code' =>'RUB' , 'name' => 'Russian Ruble', 'symbol' => 'руб' ),
        array('code' =>'SAR' , 'name' => 'Saudi Riyal', 'symbol' => '﷼' ),
        array('code' =>'SBD' , 'name' => 'Solomon Islands Dollar', 'symbol' => '$' ),
        array('code' =>'SCR' , 'name' => 'Seychelles Rupee', 'symbol' => '₨' ),
        array('code' =>'SEK' , 'name' => 'Swedish Krona', 'symbol' => 'kr' ),
        array('code' =>'SGD' , 'name' => 'Singapore Dollar', 'symbol' => '$' ),
        array('code' =>'SHP' , 'name' => 'Saint Helena Pound', 'symbol' => '£' ),
        array('code' =>'SOS' , 'name' => 'Somali Shilling', 'symbol' => 'S' ),
        array('code' =>'SRD' , 'name' => 'Surinam Dollar', 'symbol' => '$' ),
        array('code' =>'SVC' , 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$' ),
        array('code' =>'SYP' , 'name' => 'Syrian Pound', 'symbol' => '£' ),
        array('code' =>'THB' , 'name' => 'Baht', 'symbol' => '฿' ),
        array('code' =>'TRY' , 'name' => 'Turkish Lira', 'symbol' => 'TL' ),
        array('code' =>'TTD' , 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$' ),
        array('code' =>'TWD' , 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$' ),
        array('code' =>'UAH' , 'name' => 'Hryvnia', 'symbol' => '₴' ),
        array('code' =>'USD' , 'name' => 'US Dollar', 'symbol' => '$' ),
        array('code' =>'UYU' , 'name' => 'UYI Peso Uruguayo Uruguay Peso en Unidades Indexadas', 'symbol' => '$U' ),
        array('code' =>'UZS' , 'name' => 'Uzbekistan Sum', 'symbol' => 'лв' ),
        array('code' =>'VEF' , 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs' ),
        array('code' =>'VND' , 'name' => 'Dong', 'symbol' => '₫' ),
        array('code' =>'XCD' , 'name' => 'East Caribbean Dollar', 'symbol' => '$' ),
        array('code' =>'YER' , 'name' => 'Yemeni Rial', 'symbol' => '﷼' ),
        array('code' =>'ZAR' , 'name' => 'Rand', 'symbol' => 'R' )
    );
        return $currencies;
    }
	
	public static function getcountries(){
		$countries = array(
			'AF'=>'AFGHANISTAN',
			'AL'=>'ALBANIA',
			'DZ'=>'ALGERIA',
			'AS'=>'AMERICAN SAMOA',
			'AD'=>'ANDORRA',
			'AO'=>'ANGOLA',
			'AI'=>'ANGUILLA',
			'AQ'=>'ANTARCTICA',
			'AG'=>'ANTIGUA AND BARBUDA',
			'AR'=>'ARGENTINA',
			'AM'=>'ARMENIA',
			'AW'=>'ARUBA',
			'AU'=>'AUSTRALIA',
			'AT'=>'AUSTRIA',
			'AZ'=>'AZERBAIJAN',
			'AX' => 'ALAND ISLANDS',
			'BS'=>'BAHAMAS',
			'BH'=>'BAHRAIN',
			'BD'=>'BANGLADESH',
			'BB'=>'BARBADOS',
			'BY'=>'BELARUS',
			'BE'=>'BELGIUM',
			'BZ'=>'BELIZE',
			'BJ'=>'BENIN',
			'BM'=>'BERMUDA',
			'BT'=>'BHUTAN',
			'BO'=>'BOLIVIA',
			'BA'=>'BOSNIA AND HERZEGOVINA',
			'BW'=>'BOTSWANA',
			'BV'=>'BOUVET ISLAND',
			'BR'=>'BRAZIL',
			'IO'=>'BRITISH INDIAN OCEAN TERRITORY',
			'BN'=>'BRUNEI DARUSSALAM',
			'BG'=>'BULGARIA',
			'BF'=>'BURKINA FASO',
			'BI'=>'BURUNDI',
			'BQ'=>'BONAIRE',
			'KH'=>'CAMBODIA',
			'CM'=>'CAMEROON',
			'CA'=>'CANADA',
			'CV'=>'CAPE VERDE',
			'KY'=>'CAYMAN ISLANDS',
			'CF'=>'CENTRAL AFRICAN REPUBLIC',
			'TD'=>'CHAD',
			'CL'=>'CHILE',
			'CN'=>'CHINA',
			'CX'=>'CHRISTMAS ISLAND',
			'CC'=>'COCOS (KEELING) ISLANDS',
			'CO'=>'COLOMBIA',
			'KM'=>'COMOROS',
			'CG'=>'CONGO',
			'CD'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
			'CK'=>'COOK ISLANDS',
			'CR'=>'COSTA RICA',
			'CI'=>'COTE D IVOIRE',
			'HR'=>'CROATIA',
			'CU'=>'CUBA',
			'CY'=>'CYPRUS',
			'CZ'=>'CZECH REPUBLIC',
			'CW'=>'CURACAO',
			'DK'=>'DENMARK',
			'DJ'=>'DJIBOUTI',
			'DM'=>'DOMINICA',
			'DO'=>'DOMINICAN REPUBLIC',
			'TP'=>'EAST TIMOR',
			'EC'=>'ECUADOR',
			'EG'=>'EGYPT',
			'SV'=>'EL SALVADOR',
			'GQ'=>'EQUATORIAL GUINEA',
			'ER'=>'ERITREA',
			'EE'=>'ESTONIA',
			'ET'=>'ETHIOPIA',
			'FK'=>'FALKLAND ISLANDS (MALVINAS)',
			'FO'=>'FAROE ISLANDS',
			'FJ'=>'FIJI',
			'FI'=>'FINLAND',
			'FR'=>'FRANCE',
			'GF'=>'FRENCH GUIANA',
			'PF'=>'FRENCH POLYNESIA',
			'TF'=>'FRENCH SOUTHERN TERRITORIES',
			'GA'=>'GABON',
			'GM'=>'GAMBIA',
			'GE'=>'GEORGIA',
			'DE'=>'GERMANY',
			'GH'=>'GHANA',
			'GI'=>'GIBRALTAR',
			'GR'=>'GREECE',
			'GL'=>'GREENLAND',
			'GD'=>'GRENADA',
			'GP'=>'GUADELOUPE',
			'GU'=>'GUAM',
			'GT'=>'GUATEMALA',
			'GN'=>'GUINEA',
			'GW'=>'GUINEA-BISSAU',
			'GY'=>'GUYANA',
			'GG'=>'GUERNSEY',
			'HT'=>'HAITI',
			'HM'=>'HEARD ISLAND AND MCDONALD ISLANDS',
			'VA'=>'HOLY SEE (VATICAN CITY STATE)',
			'HN'=>'HONDURAS',
			'HK'=>'HONG KONG',
			'HU'=>'HUNGARY',
			'IS'=>'ICELAND',
			'IN'=>'INDIA',
			'ID'=>'INDONESIA',
			'IR'=>'IRAN, ISLAMIC REPUBLIC OF',
			'IQ'=>'IRAQ',
			'IE'=>'IRELAND',
			'IL'=>'ISRAEL',
			'IM'=>'ISLE OF MAN',
			'IT'=>'ITALY',
			'JM'=>'JAMAICA',
			'JP'=>'JAPAN',
			'JO'=>'JORDAN',
			'JE'=>'JERSEY',
			'KZ'=>'KAZAKSTAN',
			'KE'=>'KENYA',
			'KI'=>'KIRIBATI',
			'KP'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF',
			'KR'=>'KOREA REPUBLIC OF',
			'KW'=>'KUWAIT',
			'KG'=>'KYRGYZSTAN',
			'LA'=>'LAO PEOPLES DEMOCRATIC REPUBLIC',
			'LV'=>'LATVIA',
			'LB'=>'LEBANON',
			'LS'=>'LESOTHO',
			'LR'=>'LIBERIA',
			'LY'=>'LIBYAN ARAB JAMAHIRIYA',
			'LI'=>'LIECHTENSTEIN',
			'LT'=>'LITHUANIA',
			'LU'=>'LUXEMBOURG',
			'MO'=>'MACAU',
			'MK'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
			'MG'=>'MADAGASCAR',
			'MW'=>'MALAWI',
			'MY'=>'MALAYSIA',
			'MV'=>'MALDIVES',
			'ML'=>'MALI',
			'MT'=>'MALTA',
			'MH'=>'MARSHALL ISLANDS',
			'MQ'=>'MARTINIQUE',
			'MR'=>'MAURITANIA',
			'MU'=>'MAURITIUS',
			'YT'=>'MAYOTTE',
			'MX'=>'MEXICO',
			'FM'=>'MICRONESIA, FEDERATED STATES OF',
			'MD'=>'MOLDOVA, REPUBLIC OF',
			'MC'=>'MONACO',
			'MN'=>'MONGOLIA',
			'MS'=>'MONTSERRAT',
			'MA'=>'MOROCCO',
			'MZ'=>'MOZAMBIQUE',
			'MM'=>'MYANMAR',
			'NA'=>'NAMIBIA',
			'NR'=>'NAURU',
			'NP'=>'NEPAL',
			'NL'=>'NETHERLANDS',
			'AN'=>'NETHERLANDS ANTILLES',
			'NC'=>'NEW CALEDONIA',
			'NZ'=>'NEW ZEALAND',
			'NI'=>'NICARAGUA',
			'NE'=>'NIGER',
			'NG'=>'NIGERIA',
			'NU'=>'NIUE',
			'NF'=>'NORFOLK ISLAND',
			'MP'=>'NORTHERN MARIANA ISLANDS',
			'NO'=>'NORWAY',
			'OM'=>'OMAN',
			'PK'=>'PAKISTAN',
			'PW'=>'PALAU',
			'PS'=>'PALESTINIAN TERRITORY, OCCUPIED',
			'PA'=>'PANAMA',
			'PG'=>'PAPUA NEW GUINEA',
			'PY'=>'PARAGUAY',
			'PE'=>'PERU',
			'PH'=>'PHILIPPINES',
			'PN'=>'PITCAIRN',
			'PL'=>'POLAND',
			'PT'=>'PORTUGAL',
			'PR'=>'PUERTO RICO',
			'QA'=>'QATAR',
			'RE'=>'REUNION',
			'RO'=>'ROMANIA',
			'RU'=>'RUSSIAN FEDERATION',
			'RW'=>'RWANDA',
			'RS' => 'SERBIA',
			'SH'=>'SAINT HELENA',
			'KN'=>'SAINT KITTS AND NEVIS',
			'LC'=>'SAINT LUCIA',
			'PM'=>'SAINT PIERRE AND MIQUELON',
			'VC'=>'SAINT VINCENT AND THE GRENADINES',
			'WS'=>'SAMOA',
			'SM'=>'SAN MARINO',
			'ST'=>'SAO TOME AND PRINCIPE',
			'SA'=>'SAUDI ARABIA',
			'SN'=>'SENEGAL',
			'SC'=>'SEYCHELLES',
			'SL'=>'SIERRA LEONE',
			'SG'=>'SINGAPORE',
			'SK'=>'SLOVAKIA',
			'SI'=>'SLOVENIA',
			'SB'=>'SOLOMON ISLANDS',
			'SO'=>'SOMALIA',
			'ZA'=>'SOUTH AFRICA',
			'GS'=>'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
			'ES'=>'SPAIN',
			'LK'=>'SRI LANKA',
			'SD'=>'SUDAN',
			'SR'=>'SURINAME',
			'SJ'=>'SVALBARD AND JAN MAYEN',
			'SZ'=>'SWAZILAND',
			'SE'=>'SWEDEN',
			'CH'=>'SWITZERLAND',
			'SY'=>'SYRIAN ARAB REPUBLIC',
			'TW'=>'TAIWAN, PROVINCE OF CHINA',
			'TJ'=>'TAJIKISTAN',
			'TZ'=>'TANZANIA, UNITED REPUBLIC OF',
			'TH'=>'THAILAND',
			'TG'=>'TOGO',
			'TK'=>'TOKELAU',
			'TO'=>'TONGA',
			'TT'=>'TRINIDAD AND TOBAGO',
			'TN'=>'TUNISIA',
			'TR'=>'TURKEY',
			'TM'=>'TURKMENISTAN',
			'TC'=>'TURKS AND CAICOS ISLANDS',
			'TV'=>'TUVALU',
			'TW'=>'TAIWAN',
			'UG'=>'UGANDA',
			'UA'=>'UKRAINE',
			'AE'=>'UNITED ARAB EMIRATES',
			'GB'=>'UNITED KINGDOM',
			'US'=>'UNITED STATES',
			'UM'=>'UNITED STATES MINOR OUTLYING ISLANDS',
			'UY'=>'URUGUAY',
			'UZ'=>'UZBEKISTAN',
			'VU'=>'VANUATU',
			'VE'=>'VENEZUELA',
			'VN'=>'VIET NAM',
			'VG'=>'VIRGIN ISLANDS, BRITISH',
			'VI'=>'VIRGIN ISLANDS, U.S.',
			'WF'=>'WALLIS AND FUTUNA',
			'EH'=>'WESTERN SAHARA',
			'YE'=>'YEMEN',
			'YU'=>'YUGOSLAVIA',
			'ZM'=>'ZAMBIA',
			'ZW'=>'ZIMBABWE',
			'ME'=>'MONTENEGRO',
			'BL'=>'SAINT BARTHELEMY',
			'MF'=>'SAINT MARTIN',
			'SX'=>'SINT MAARTEN',
			'SS'=>'SOUTH SUDAN',
			'IC'=>'SPAIN (CANARY ISLANDS)',
			'EA'=>'SPAIN (CEUTA AND MELILLA)',
			'TL'=>'TIMOR-LESTE'
		  );
		  return $countries;
	}
	
	public function order_notes() {
        return $this->hasOne('LMS\OrderNote', 'order_id', 'id')->where('status', 'Y')->orderBy('id', 'desc')->take(1);
    }
}
